[general]
  runDirRoot = '../runs/test'
  inputDir = './input'
  overwrite = false
  fields = ['F1','F2','F3','F4']
  nProcessor = 1
  reaches = ['R601','R602','R603','R604','R605']
[xroutingdrainage]
  outputVars = '/LineicMassDrainage'
  output_lineic_file = '${general.inputDir}/LineicMassDra.csv'
  xdrainagerouting_file = '${general.inputDir}/xdrainagerouting.csv'
  fieldsAreaFile = '${general.inputDir}/fields_area.csv'
  fieldsMassFluxFile  = '${general.inputDir}/Jmass.csv'
  reachesLengthFile = '${general.inputDir}/reaches_length.csv'